Api end points
tc-ca/EQM-GQE.API pull request #6
Opened 2021-06-14 18:53 UTC by boshr-tc

EQM - API Endpoint - Post Questionnaire Template

2021-06-14 19:01 UTC, MOULAST requested changes
looks like we have logical code in our front end API layer, let's move this to a logical layer and pass in an interface to interact with. The logic layer will work with the data layer. This will fee redundant for the post. but when we have more complex logical to implement we will be happy to have it.

Also I don't see any unit tests for this. I would like to see them for logical (testing business logic and mocking the data layer) and API (Testing endpoints for different error cases and happy path (again mocking the data layer).

2021-06-14 19:01 UTC, MOULAST commented on EQM-GQE.API/Controllers/QuestionnaireController.cs
> +            Questionnaire questionnaire = new ()
We should be passing the oQuestionnaire into the logic layer. Then the logic layer will be responsible for calling the Data Layer and storing it in the database.

2021-06-14 19:01 UTC, MOULAST commented on EQM-GQE.API/Controllers/QuestionnaireController.cs
> +            Questionnaire questionnaire = new ()
Also, I would like to see some unit tests for both the logical layer and the API layer.

The api layer should test for error catching like a null questionnaire and other cases. Right now this endpoint will always respond with Ok which is not the case if there is an error.

2021-06-14 19:01 UTC, MOULAST commented on EQM-GQE.API/Controllers/QuestionnaireController.cs
> +        private readonly IQuestionnaireRepository _questionnaireRepository;
you can probably move this to the logical layer once it is implemented and pass in the logical interface instead.

2021-06-15 17:50 UTC, MOULAST commented
@boshr-tc can we auto migrate the DB as well on start of the application to ensure we have the most up to date DB.

2021-06-15 20:50 UTC, boshr-tc commented on EQM-GQE.API/Controllers/QuestionnaireController.cs
> +        private readonly IQuestionnaireRepository _questionnaireRepository;
Moved private readonly IQuestionnaireRepository _questionnaireRepository; to the logical layer once it is implemented and pass in the logical interface instead.

2021-06-16 15:08 UTC, boshr-tc commented on EQM-GQE.API/Controllers/QuestionnaireController.cs
> +            Questionnaire questionnaire = new ()
Passed the oQuestionnaire into the logic layer. Then the logic layer will be responsible for calling the Data Layer and storing it in the database.

Confirmed with Stephen, we will close this PR without the Unit test work, Rajib will create a new branch and work on the unit test.

2021-06-17 21:00 UTC, MOULAST approved these changes
looks good now

2021-06-17 21:00 UTC, MOULAST commented on EQM-GQE.API/Controllers/QuestionnaireController.cs
> +            Questionnaire questionnaire = new ()
Miscommunication, I want the unit test done as part of this PR.

2021-06-17 21:00 UTC, merged